resilience4j.circuitbreaker:
  instances:
    orderServiceCircuitBreaker:
      registerHealthIndicator: true
      failureRateThreshold: 50 # Percentage of failed calls after which the circuit breaker opens
      waitDurationInOpenState: 10000ms # Time to wait before trying the next call
      permittedNumberOfCallsInHalfOpenState: 3 # Number of calls allowed to test if the service is available
      slidingWindowSize: 5 # Number of calls to consider for calculating failure rate
      recordExceptions:
        - java.io.IOException
        - org.springframework.web.reactive.function.client.WebClientRequestException
        - java.net.ConnectException
      ignoreExceptions:
        - org.springframework.web.client.HttpServerErrorException

management:
  endpoints:
    web:
      exposure:
        include: health,info